name: Create Release

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Verify Site Accessibility
    types:
      - completed
  workflow_dispatch:

env:
  PLUGIN_SLUG: "wpoven-image-optimization"
  WP_PATH: /var/www/html
  PLUGIN_PATH: /var/www/html/wp-content/plugins/wpoven_imageoptim
  WORDPRESS_URL: http://localhost
  ADMIN_USER: admin
  ADMIN_PASSWORD: Wpoven@baseapp1
  ADMIN_EMAIL: admin@example.com
  
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: needs.carify-site.outputs.site-status == 'success'
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set version variables
        id: versions
        run: |
          RELEASE_DATE=$(date +'%Y-%m-%d')
          PLUGIN_VERSION="${{ github.event.inputs.plugin_version || '1.0.0' }}"
          ZIP_NAME="${{ env.PLUGIN_SLUG }}-${RELEASE_DATE}.zip"

          echo "release_date=$RELEASE_DATE" >> $GITHUB_OUTPUT
          echo "plugin_version=$PLUGIN_VERSION" >> $GITHUB_OUTPUT
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create plugin package
        run: |
          mkdir -p releases
          (cd source && zip -r "../releases/${{ steps.versions.outputs.zip_name }}" . -x ".*" -x "__MACOSX" -x "*.git*")
          cp "releases/${{ steps.versions.outputs.zip_name }}" "./${{ steps.versions.outputs.zip_name }}"

      - name: Update README
        run: |
          sed -i "s/\*\*Tested up to:\*\* [0-9.]*/**Tested up to:** ${{ github.event.inputs.wp_version || '6.6.2' }}/" README.md
          sed -i "s/\*\*Stable tag:\*\* [0-9.]*/**Stable tag:** ${{ steps.versions.outputs.plugin_version }}/" README.md
          sed -i "s|/releases/download/[0-9.]*/wpoven-image-optimization-[0-9-]*.zip|/releases/download/${{ steps.versions.outputs.plugin_version }}/${{ steps.versions.outputs.zip_name }}|" README.md
          sed -i "s/Tested up to: [0-9.]*/Tested up to: ${{ github.event.inputs.wp_version || '6.6.2' }}/" README.txt
          sed -i "s/Stable tag: [0-9.]*/Stable tag: ${{ steps.versions.outputs.plugin_version }}/" README.txt
          sed -i "s|/releases/download/[0-9.]*/wpoven-image-optimization-[0-9-]*.zip|/releases/download/${{ steps.versions.outputs.plugin_version }}/${{ steps.versions.outputs.zip_name }}|" README.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.versions.outputs.zip_name }}
          tag_name: ${{ steps.versions.outputs.plugin_version }}
          name: "WPOven Image Optimization v${{ steps.versions.outputs.plugin_version }}"
          body: |
            🚀 WPOven Image Optimization Release v${{ steps.versions.outputs.plugin_version }}
            Release Date: ${{ steps.versions.outputs.release_date }}
            Tested with WordPress: ${{ github.event.inputs.wp_version || '6.6.2' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md README.txt releases/
          git commit -m "Release v${{ steps.versions.outputs.plugin_version }} - Update README and add release files" || echo "No changes to commit"
          git push
            
