name: PHP Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PLUGIN_SLUG: "wpoven-image-optimization"
  WP_PATH: /var/www/html
  PLUGIN_PATH: /var/www/html/wp-content/plugins/wpoven_imageoptim
  WORDPRESS_URL: http://localhost
  ADMIN_USER: admin
  ADMIN_PASSWORD: Wpoven@baseapp1
  ADMIN_EMAIL: admin@example.com


jobs:
  php-check:
    name: Setup PHP
    runs-on: ubuntu-latest
    outputs:
      php-status: ${{ steps.php-check.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml, mysql
          coverage: none

      - name: Verify PHP installation
        run: php -v

      - name: Set PHP check status
        id: php-check
        run: echo "status=success" >> $GITHUB_OUTPUT
